services:
  - type: web
    name: google-home-mcp
    runtime: node
    plan: free
    buildCommand: npm ci && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: AUTH_TOKEN
        generateValue: true
      - key: PORT
        value: 10000
    healthCheckPath: /health
    autoDeploy: true